### ISSUE TITLE
Issue with seed in tabular model

### ISSUE THREAD

**Issue by suvrathiran** [fastai/fastai2#112] opened 2020-02-18 06:24 UTC
Hi,

I am facing issue setting seed value for tabular model on CPU. This is what I have tried. 

```
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
seed_everything(SEED)
```

Post doing above I still get different values for torch.seed()
Also, the results are different. I am not sure if I am missing out something basic :(

Thanks in advance.

**Comment by sgugger** [comment] 2020-02-18 14:44
AFAICT you are seeding everything already. You should post your problem on the forum with the code you are then using to gather your data and train your model, as there will be more people to help here.
Closing this as it's not a bug in the library from what I can see, please reopen if debugging discovers a reproducible bug in fastai,

**Closed by sgugger** 2020-02-18 14:44 UTC
