### ISSUE TITLE
Scikit transformer wrapper contribution

### ISSUE THREAD

**Issue by feribg** [fastai/fastai2#234] opened 2020-04-02 03:19 UTC
Are you interested in the following being contributed:

```
from sklearn.base import TransformerMixin
from typing import List
class ScikitTransform(TabularProc):
    """
    Wraps a scikit learn transformer in a fastai tabular transformer
    """
    order = 2
    def __init__(self, sk_tf: TransformerMixin, feats: List = []):
        super().__init__()
        self.transformer: TransformerMixin = sk_tf
        self.feats: List = feats
    
    def setups(self, dsets): 
        if len(self.feats) == 0:
            self.feats = dsets.conts.columns
        self.transformer.fit(dsets[self.feats])
    
    def encodes(self, to): 
        to[self.feats] = self.transformer.transform(to[self.feats])
    
    def decodes(self, to): 
        to[self.feats] = self.transformer.inverse_transform(to[self.feats])

procs = [ScikitTransform(sk_tf=MinMaxScaler(),feats=cont_names)]
```

Standartization is not always optimal for tabular data.

**Comment by sgugger** [comment] 2020-04-02 11:50
Sure, it can be added to the `tabular.core` notebook with a test. Closing the issue as it's not a bug. Discussing feature development should be done on the [forum](https://forums.fast.ai/).

**Closed by sgugger** 2020-04-02 11:50 UTC
