### ISSUE TITLE
Best way to contribute to this project? 

### ISSUE THREAD

**Issue by codeamt** [fastai/fastai2#346] opened 2020-05-06 23:02 UTC
Would like to use fastai2 in a project; wondering, what’s the best way to contribute to this repo (or is there a task queue)? Looking forward!

**Comment by sgugger** [comment] 2020-05-07 11:46
The best way is to look at the [forum](https://forums.fast.ai/): either suggest a feature here and get feedback from users before making a PR or spotting the topics with Help Needed flags (currently, the docs).

Closing this here since we use the forum for everything that's not a bug.

**Closed by sgugger** 2020-05-07 11:46 UTC
