### ISSUE TITLE
Side effect with crop_pad on TensorPoint

### ISSUE THREAD

**Issue by antoinebon** [fastai/fastai2#373] opened 2020-05-22 21:55 UTC
As illustrated in the following gist https://gist.github.com/antoinebon/368ec4a5a996eefd179edfaced7db18d, resizing a TensorPoint with crop_pad replicates the original TensorPoint's `__dict__` (in `Tensor.set_meta`). Therefore, changing the `_meta` of the resized TensorPoint also also changes the `_meta` of the orignal TensorPoint

This side effect is not very transparent and probably not desired. What do you think?

**Comment by sgugger** [comment] 2020-05-23 13:16
Eh, no, it doesn't look like something we want. Will try to come up with a fix.
Thanks for the reproducer!

**Comment by muellerzr** [comment] 2020-07-13 20:40
Since this was merged with a fix, can this issue be closed @antoinebon ?

**Comment by antoinebon** [comment] 2020-07-20 11:15
@muellerzr I don't think this issue is fixed, at least it was not fixed in #382.

**Comment by jph00** [comment] 2020-07-28 22:21
Fixed now!

**Closed by jph00** 2020-07-28 22:21 UTC
