### ISSUE TITLE
Warp causing Nan values

### ISSUE THREAD

**Issue by bearpelican** [fastai/fastai2#327] opened 2020-04-23 21:51 UTC
I'm getting a non-deterministic bug where I'm getting a NaN value when applying warp.
It specifically happens here when dividing by coords[...,:2]: https://github.com/fastai/fastai2/blob/master/fastai2/vision/augment.py#L588

I only know because I've added an isnan check on that line. But unable to reproduce reliably

**Comment by sgugger** [comment] 2020-04-24 11:51
Eh, I'd need a reproducer to fix.

**Comment by bearpelican** [comment] 2020-04-24 18:21
Well, it took 80 epochs for my model/loss to start NaN'ing out, but at least we should be able to reproduce it now. Hopefully, this'll save others the headache =)

https://gist.github.com/bearpelican/0314aee9483a25789f09f0e7a95d1594

**Comment by bearpelican** [comment] 2020-04-24 18:36
Updated notebook, should be faster to repro:
https://gist.github.com/bearpelican/84b3df2858a180098087d79ed1dddbdc

**Comment by sgugger** [comment] 2020-04-24 18:56
It's not something I can really debug and since it seems to only happen once in a while, the best way to address is probably to cancel data augmentation when it does happen. So try to do all of what's in the function you pointed and then just return the initial `coords` if we get NaNs. Does that sound right to you?

**Comment by bearpelican** [comment] 2020-04-24 20:25
Yup I totally agree.

The only other way I can think of is to add an eps when coords[...,2] == 0, but I'm not sure how that would affect the function.

**Comment by sgugger** [comment] 2020-04-24 20:35
Added the fix, can you confirm it works?

**Comment by bearpelican** [comment] 2020-04-24 21:25
Works for me --- if you change this line to coords1:
https://github.com/fastai/fastai2/blob/5e88815be2491853271cb5082d90835cf530ba17/fastai2/vision/augment.py#L589

**Comment by sgugger** [comment] 2020-04-24 21:28
Bad export, sorry. Should be fixed.

**Closed by sgugger** 2020-04-24 21:28 UTC
